### ISSUE TITLE
Replace tokio with mio in resolver?

### ISSUE THREAD

**Issue by pusateri** [NLnetLabs/domain#23]
tokio brings in a lot of packages and all the resolver really needs is a way to do async io. mio does this and it might be better to use it directly than depend on tokio.

**Comment by partim** [comment]
I imagine that most people using the crate will do more networking apart from DNS and would want to do that with some abstraction over pure mio. At the moment, Tokio is the de-facto standard for that, so I think it makes sense to build on that. That said, there is quite a bit of movement in that space right now. We should revisit this after the dust around async/await has settled a bit.

One thing we can do is to not depend on the big `tokio` crate but only on those components we actually use. I’ll have a look and, if that leads to a lower dependency count, make a PR.

**Comment by partim** [comment]
Having now ported the resolver to use async functions, I feel that the simplicity of the resulting code is a good argument in favour of keep using Tokio and possibly supporting alternative runtimes. Particularly since I expect the code to become more complex over time – the resolver feels rather simple right now.

That said, maybe it is possible to separate the code that does the creates queries and processes responses from the actual network IO and make that generic? Then a version of the resolver using mio should be possible.

**Comment by pusateri** [comment]
Tokio has gotten much better with async/await  support in 0.2. Before, I found Tokio to be unusable in anything but sample code. But they have made a lot of progress and this isn't as important to me now.

**Comment by partim** [comment]
We'll improve non-async use of the resolver in the next (breaking) release by hiding the async-ness. We might also explore support for async-std or other systems later on.

I'll close the issue for the time being.
