### ISSUE TITLE
Collaboration with trust-dns?

### ISSUE THREAD

**Issue by dsvensson** [NLnetLabs/domain#30]
I'm not affiliated with the project, I'm just curious as to why you decided to roll your own DNS library instead of contributing to what's missing in trust-dns instead? For the sake of diversity, or you have completely different goals, or some other reason?

https://github.com/bluejekyll/trust-dns

**Comment by partim** [comment]
The project started as a means for me learning both Rust and DNS. It has a slightly different focus than Trust-DNS – it is more about providing building blocks for specialized DNS applications rather than a generic server. For that reason and indeed diversity (we kind of have a tradition of providing alternative implementations at NLnet Labs) I think it is worth keeping even if, sadly, I don’t quite have as much time to spend on it as I would want to.
