### ISSUE TITLE
domain 0.10.2 built failed after upgrading

### ISSUE THREAD

**Issue by Xuanwo** [NLnetLabs/domain#411]
Hi, @partim. Thank you for maintaining this library.

I noticed that `0.10.2` is broken after upgrading:

```shell
error[E0433]: failed to resolve: could not find `zonetree` in the crate root
   --> /home/xuanwo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/domain-0.10.2/src/net/xfr/protocol/interpreter.rs:8:12
    |
8   | use crate::zonetree::types::ZoneUpdate;
    |            ^^^^^^^^ could not find `zonetree` in the crate root
    |
note: found an item that was configured out
   --> /home/xuanwo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/domain-0.10.2/src/lib.rs:177:9
    |
177 | pub mod zonetree;
    |         ^^^^^^^^
    = note: the item is gated behind the `unstable-zonetree` feature

error[E0433]: failed to resolve: could not find `zonetree` in the crate root
   --> /home/xuanwo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/domain-0.10.2/src/net/xfr/protocol/iterator.rs:9:12
    |
9   | use crate::zonetree::types::ZoneUpdate;
    |            ^^^^^^^^ could not find `zonetree` in the crate root
    |
note: found an item that was configured out
   --> /home/xuanwo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/domain-0.10.2/src/lib.rs:177:9
    |
177 | pub mod zonetree;
    |         ^^^^^^^^
    = note: the item is gated behind the `unstable-zonetree` feature

```

Would you consider releasing a `0.10.3` to address this? Thanks in advance.

**Comment by ximon18** [comment]
Hi @Xuanwo,

Thank you for trying the release and thank you very much for reporting this issue, I'm sorry that you encountered a problem.

I wonder if you are building using a subset of enabled features. I ask because our GitHub Actions CI builds and tests are passing, and `cargo build` and `cargo build --all-features` seem to work for me.

I can however produce a similar error if I build with `cargo build --features net` so we should fix that.

Are you building with some specific features enabled? And if so, which ones?

Thanks,

Ximon

**Comment by Xuanwo** [comment]
> I can however produce a similar error if I build with `cargo build --features net` so we should fix that.
> 
> Are you building with some specific features enabled? And if so, which ones?

Hi, thank you for the quick response. We don't use `domain` directly; it's a deep dependency used by others. I'm currently unsure about which features have been enabled.

**Comment by sjoerdsimons** [comment]
Fwiw i'm hitting the same issues using `features = ["serde", "tsig", "resolv", "tokio"]`, i've not pinned down what triggers it exactly though

**Comment by ximon18** [comment]
> Fwiw i'm hitting the same issues using `features = ["serde", "tsig", "resolv", "tokio"]`, i've not pinned down what triggers it exactly though

That might be caused by `tsig` as we touched that in the unstable feature work we have been doing recently.

Testing all, or at least more, feature combinations is a bit problematic due to the time it to takes (though maybe a GitHub Actions workflow matrix could be used to do it in parallel) but maybe we should do it at least as a pre-release check.

**Comment by ximon18** [comment]
The `fix-compile-with-feature-net` branch works with features `net` and also with `serde,resolv,tsig,tokio` for me. If you are able to test that please let us know if it fixes it for you.

**Comment by sjoerdsimons** [comment]
CI ran through successfully: https://github.com/sjoerdsimons/ddns-letsencrypt-tool/commit/f5e0cd22fd06b3f00266a1b0f14571dd0bf2faed so looks all good :)

**Comment by ximon18** [comment]
@Xuanwo - We'll make a 0.10.3 release as soon as reviews and a bit more feature gate compilation testing are done.

**Comment by Xuanwo** [comment]
> @Xuanwo - We'll make a 0.10.3 release as soon as reviews and a bit more feature gate compilation testing are done.

Perfect. Thanks a lot for your quick response!
